### ISSUE TITLE
Add advanced search capabilities with filtering and sorting options for IGDB

### ISSUE THREAD

**Issue by IgnisDa** [IgnisDa/ryot#1531]
Context: https://discord.com/channels/1239445721502056459/1406681661147451513

## Description
Currently, the search functionality is basic with only simple title search. This feature request aims to enhance search capabilities by adding comprehensive filtering and sorting options to make browsing for new titles much easier.

#### Filtering Options
- **Genres** - Multi-select with search/select hybrid component
- **Platforms** - Multi-select with search/select hybrid component
  - Include checkbox for "exclusives only" (games with single platform)
- **Game Modes** - Single-player/Multi-player filtering
- ~**Series/Franchise** - Filter by game series (Super Mario, The Legend of Zelda, etc.)~
- ~**Developers** - Filter by main developers/involved companies~
- ~**Licensed Games Only** - Exclude unlicensed games by filtering out keywords:~
  ~- homebrew, unofficial, bootleg, unreleased, canceled games, unofficial port, unlicensed game, fangame~
  ~- Games without release dates~

~#### Sorting Options~ (https://github.com/IgnisDa/ryot/issues/1531#issuecomment-3216242916)
- **Name** (alphabetical)
- **First Release Date**
- **Rating** (numerical rating or aggregated rating)
- **Time to Beat**
- **Provider Rating**

**Comment by RandyWeyer** [comment]
I would like to add "region" in there to exclude all those Japanese games most people have no way of playing. For some retro consoles that's almost half the library

**Comment by IgnisDa** [comment]
> I would like to add "region" in there to exclude all those Japanese games most people have no way of playing. For some retro consoles that's almost half the library


<img width="1208" height="504" alt="Image" src="https://github.com/user-attachments/assets/abd47a49-121f-47b8-ba0d-17917189dd50" />
IGDB does not have a region filter for games. In the UI as well as the API.

**Comment by RandyWeyer** [comment]
It's in the extras section on the site.

<img width="864" height="841" alt="Image" src="https://github.com/user-attachments/assets/13c6e804-3345-49a5-a881-23ae56915751" />

I think it's game_localizations in the API.

<img width="864" height="514" alt="Image" src="https://github.com/user-attachments/assets/11e2a241-293f-4b4d-bf01-4cedb98722af" />

**Comment by RandyWeyer** [comment]
Also, I'm noticing that the user ratings seem to be much more useful than the critic ratings.

**Comment by IgnisDa** [comment]
@RandyWeyer I have pushed `ghcr.io/ignisda/ryot:pr-1532` docker image with a few of these changes. Can you please take it for a test drive? Make sure to create a fresh db instance and not connect it with your existing db.

**Comment by RandyWeyer** [comment]
This is definitely a promising start. It's already much more useful. I just noticed a few bugs.

The first thing I noticed is that you can't remove the last item in the search box. I had to remove the filters with the no-filter button and type something else in the search box to get it removed and refreshed. 

Also usually when I select an option, the search doesn't refresh right away. This makes it seem like it's not working right.

Region should contain at least North America, Europe, Japan. Mine is only showing Japan, Europe and Korean.

The regions don't seem to be working right. When searching for "Mario," selecting Japan looks right, but for Europe nothing shows up. The other ones seem to be working.

It would be good to alphabetize the dropdowns. It takes forever to find anything by scrolling through it.

Looks pretty good though.

**Comment by IgnisDa** [comment]
> It would be good to alphabetize the dropdowns. It takes forever to find anything by scrolling through it.

I did this, but btw you can also type in your input.

> Region should contain at least North America, Europe, Japan. Mine is only showing Japan, Europe and Korean.

I noticed this too but the https://api-docs.igdb.com/#region endpoints just return the ones that are currently being shown. I am not sure which API returns the ones you mentioned.

> The first thing I noticed is that you can't remove the last item in the search box.

Fixed.

Please pull the image again and test it out.

**Comment by RandyWeyer** [comment]
Probably caught you in the middle of doing something. Getting an error just going to the search page.

`ZodError: [
  {
    "expected": "string",
    "code": "invalid_type",
    "path": [
      "googleBooksPassRawQuery"
    ],
    "message": "Invalid input: expected string, received undefined"
  },
  {
    "expected": "string",
    "code": "invalid_type",
    "path": [
      "igdbAllowGamesWithParent"
    ],
    "message": "Invalid input: expected string, received undefined"
  }
]`

**Comment by IgnisDa** [comment]
Please go ahead and try now

**Comment by RandyWeyer** [comment]
I could get onto the search page and the UI bugs seem to be fixed. 

One bug still. All the drop-downs are limited to 10 items.

The region drop down is still sticking out. Region is kinda all over on the API. I found two separate tables listing out the regions. I think it's actually under https://api-docs.igdb.com/#release-date. So it's https://api.igdb.com/v4/release_dates, then get `release_region` which enumerates the following table.

<img width="215" height="510" alt="Image" src="https://github.com/user-attachments/assets/9e5bcaa3-8bdc-451f-b736-5b52318babf9" />

I also saw this example in  the documentation for getting platform exclusives. 
> Get all games that are playstation 4 exclusives
>fields name,category,platforms;
>where category = 0 & platforms = 48;

Other than that, this looks good as far as filtering goes.

**Comment by IgnisDa** [comment]
@RandyWeyer I have pushed the changes for regions. Please test those changes as well. Working on platform exclusives next.

**Comment by RandyWeyer** [comment]
Everything is looking good now. 

I'm not sure if platform exclusives are working yet. It's not removing games like `Road Avenger` and `Ivan ''Ironman'' Stewart's Super Off Road` which each have like 8 consoles listed. 

I see this in the code:
`     if platform_exclusives_only {
            filters.push("category = 0".to_string());
        }` 

Is this putting `category = 0` at the end, because I think it needs to be in the `platform` part of the query. And actually it looks like that is being deprecateed anyways. Use `platform_type` instead:

https://api-docs.igdb.com/#platform

**Comment by IgnisDa** [comment]
Removed the platform exclusives checkbox completely and added a new multiselect for game_type (`game.category` was deprecated for this)

**Comment by IgnisDa** [comment]
Sorting will not be possible. Getting this error:

```
[\n  {\n    \"title\": \"Not Acceptable Query\",\n    \"status\": 406,\n    \"cause\": \"Your query has both search and sort\",\n    \"details\": \"Search is sorting on relevancy and therefore sort is not applicable on search\"\n  }\n
```

I have pushed the other changes. Please test it out and let me know.

**Comment by RandyWeyer** [comment]
Well, there's our answer to if the API can do the same thing as imported collections. We pushed it to its limits and it can't quite get there. 

I noticed pressing the no filter button in the corner of the modal doesn't return anything. I had to type something in the search box to get it to refresh. 

For the search/drop-downs, you have to click to cancel the selection twice if it's the last one in the box. 

Other than that it looks great. Much more function here than there was previously.

**Comment by IgnisDa** [comment]
Thanks for the feedback. The issues you mentioned were due to some pre-existing bugs and I am working on fixing them. Thanks for helping me test!

**Comment by RandyWeyer** [comment]
Thanks for the chance to shape this feature. It turned out pretty good!
