### ISSUE TITLE
application error after update

### ISSUE THREAD

**Issue by TWART016** [IgnisDa/ryot#736]
I updated from 4.1.3 to 4.3.16 and get an Application Error:
![image](https://github.com/IgnisDa/ryot/assets/29805669/263884f2-a010-4cb4-82ab-90de72060e34)

After starting the Container I get this logs:
```
ryot        | [backend] 2024-04-03T23:39:21.766899Z  INFO ryot: Running version: 4.3.16
ryot        | [backend] 2024-04-03T23:39:22.265507Z  INFO sea_orm_migration::migrator: Applying all pending migrations
ryot        | [backend] 2024-04-03T23:39:22.341289Z  INFO sea_orm_migration::migrator: Applying migration 'm20240121_add_updated_at_to_seen'
ryot        | [backend] 2024-04-03T23:39:22.614089Z  INFO sea_orm_migration::migrator: Migration 'm20240121_add_updated_at_to_seen' has been applied
ryot        | [backend] 2024-04-03T23:39:22.632323Z  INFO sea_orm_migration::migrator: Applying migration 'm20240121_remove_useless_section_from_dashboard'
ryot        | [backend] 2024-04-03T23:39:22.655367Z  INFO sea_orm_migration::migrator: Migration 'm20240121_remove_useless_section_from_dashboard' has been applied
ryot        | [backend] 2024-04-03T23:39:22.657684Z  INFO sea_orm_migration::migrator: Applying migration 'm20240122_remove_useless_section_from_dashboard'
ryot        | [backend] 2024-04-03T23:39:22.659939Z  INFO sea_orm_migration::migrator: Migration 'm20240122_remove_useless_section_from_dashboard' has been applied
ryot        | [backend] 2024-04-03T23:39:22.664207Z  INFO sea_orm_migration::migrator: Applying migration 'm20240126_set_comment_to_null_for_measurements'
ryot        | [backend] 2024-04-03T23:39:22.673463Z  INFO sea_orm_migration::migrator: Migration 'm20240126_set_comment_to_null_for_measurements' has been applied
ryot        | [backend] 2024-04-03T23:39:22.676728Z  INFO sea_orm_migration::migrator: Applying migration 'm20240128_change_calendar_event_data'
ryot        | [proxy] {"level":"info","ts":1712187563.1086802,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":""}
ryot        | [proxy] {"level":"warn","ts":1712187563.1141078,"logger":"admin","msg":"admin endpoint disabled"}
ryot        | [proxy] {"level":"warn","ts":1712187563.1163468,"logger":"http.auto_https","msg":"automatic HTTPS is completely disabled for server","server_name":"srv0"}
ryot        | [proxy] {"level":"info","ts":1712187563.1164153,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc0001c4280"}
ryot        | [proxy] {"level":"info","ts":1712187563.1786497,"logger":"tls","msg":"cleaning storage unit","description":"FileStorage:/home/ryot/.local/share/caddy"}
ryot        | [proxy] {"level":"info","ts":1712187563.1791077,"logger":"tls","msg":"finished cleaning storage units"}
ryot        | [proxy] {"level":"info","ts":1712187563.1803057,"logger":"http.log","msg":"server running","name":"srv0","protocols":["h1","h2","h3"]}
ryot        | [proxy] {"level":"info","ts":1712187563.182969,"msg":"autosaved config (load with --resume flag)","file":"/home/ryot/.config/caddy/autosave.json"}
ryot        | [proxy] {"level":"info","ts":1712187563.1829896,"msg":"serving initial configuration"}
postgres_1  |
postgres_1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres_1  |
postgres_1  | 2024-04-03 23:39:21.539 UTC [1] LOG:  starting PostgreSQL 16.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 13.2.1_git20231014) 13.2.1 20231014, 64-bit
postgres_1  | 2024-04-03 23:39:21.541 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1  | 2024-04-03 23:39:21.541 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1  | 2024-04-03 23:39:21.608 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1  | 2024-04-03 23:39:21.638 UTC [23] LOG:  database system was shut down at 2024-04-03 23:38:54 UTC
postgres_1  | 2024-04-03 23:39:21.722 UTC [1] LOG:  database system is ready to accept connections

postgres_1  | 2024-04-03 23:40:22.086 UTC [32] LOG:  skipping vacuum of "seen" --- lock not available
postgres_1  | 2024-04-03 23:41:22.132 UTC [33] LOG:  skipping vacuum of "seen" --- lock not available
postgres_1  | 2024-04-03 23:41:30.394 UTC [32] ERROR:  canceling autovacuum task
postgres_1  | 2024-04-03 23:41:30.394 UTC [32] CONTEXT:  while vacuuming index "calendar_event-date-metadataid-info__uq-idx" of relation "public.calendar_event"
postgres_1  |   automatic vacuum of table "postgres.public.calendar_event"
postgres_1  | 2024-04-03 23:42:21.990 UTC [34] LOG:  skipping vacuum of "seen" --- lock not available
postgres_1  | 2024-04-03 23:42:21.990 UTC [34] LOG:  skipping vacuum of "calendar_event" --- lock not available
postgres_1  | 2024-04-03 23:42:27.029 UTC [21] LOG:  checkpoint starting: wal

```

After open the URL I get these messages
```
ryot        | [frontend] GET /auth/login?redirectTo=%2F 500 - - 1144.256 ms
ryot        | [backend] 2024-04-03T23:45:11.642770Z  INFO sea_orm_migration::migrator: Migration 'm20240202_1_normalize_calendar_events_data' has been applied
ryot        | [backend] 2024-04-03T23:45:11.810426Z  INFO sea_orm_migration::migrator: Applying migration 'm20240202_2_normalize_reviews_data'
ryot        | [backend] 2024-04-03T23:45:11.907350Z  INFO sea_orm_migration::migrator: Migration 'm20240202_2_normalize_reviews_data' has been applied
ryot        | [backend] 2024-04-03T23:45:11.907974Z  INFO sea_orm_migration::migrator: Applying migration 'm20240202_4_normalize_metadata_data'
ryot        | [frontend] GET / 302 - - 139.365 ms
ryot        | [proxy] {"level":"error","ts":1712187917.6909285,"logger":"http.log.error","msg":"dial tcp 127.0.0.1:5000: connect: connection refused","request":{"remote_ip":"127.0.0.1","remote_port":"50256","client_ip":"127.0.0.1","proto":"HTTP/1.1","method":"POST","host":"localhost:8000","uri":"/backend/graphql","headers":{"User-Agent":["node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"],"Accept-Encoding":["gzip,deflate"],"Connection":["keep-alive"],"Content-Type":["application/json"],"Accept":["*/*"],"Content-Length":["146"]}},"duration":0.009368577,"status":502,"err_id":"yhiwpifj6","err_trace":"reverseproxy.statusError (reverseproxy.go:1265)"}
ryot        | [frontend] ClientError: GraphQL Error (Code: 502): {"response":{"error":"","status":502,"headers":{}},"request":{"query":"query CoreEnabledFeatures {\n  coreEnabledFeatures {\n    fileStorage\n    signupAllowed\n  }\n}"}}
ryot        | [frontend]     at makeRequest (file:///home/ryot/node_modules/graphql-request/src/index.ts:426:11)
ryot        | [frontend]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
ryot        | [frontend]     at getCoreEnabledFeatures (file:///home/ryot/build/server/index.js?t=1712132349000:737:35)
ryot        | [frontend]     at loader$1 (file:///home/ryot/build/server/index.js?t=1712132349000:13378:27)
ryot        | [frontend]     at Object.callRouteLoaderRR (/home/ryot/node_modules/@remix-run/server-runtime/dist/data.js:52:16)
ryot        | [frontend]     at callLoaderOrAction (/home/ryot/node_modules/@remix-run/router/router.ts:4043:16)
ryot        | [frontend]     at async Promise.all (index 1)
ryot        | [frontend]     at loadRouteData (/home/ryot/node_modules/@remix-run/router/router.ts:3320:19)
ryot        | [frontend]     at queryImpl (/home/ryot/node_modules/@remix-run/router/router.ts:3101:20)
ryot        | [frontend]     at Object.query (/home/ryot/node_modules/@remix-run/router/router.ts:2977:18) {
ryot        | [frontend]   response: {
ryot        | [frontend]     error: '',
ryot        | [frontend]     status: 502,
ryot        | [frontend]     headers: Headers { [Symbol(map)]: [Object: null prototype] }
ryot        | [frontend]   },
ryot        | [frontend]   request: {
ryot        | [frontend]     query: 'query CoreEnabledFeatures {\n' +
ryot        | [frontend]       '  coreEnabledFeatures {\n' +
ryot        | [frontend]       '    fileStorage\n' +
ryot        | [frontend]       '    signupAllowed\n' +
ryot        | [frontend]       '  }\n' +
ryot        | [frontend]       '}',
ryot        | [frontend]     variables: undefined
ryot        | [frontend]   }
ryot        | [frontend] }
ryot        | [frontend] [Error: Unexpected Server Error]
ryot        | [frontend] GET /auth/login?redirectTo=%2F 500 - - 285.337 ms
ryot        | [backend] 2024-04-03T23:46:04.520651Z  INFO sea_orm_migration::migrator: Migration 'm20240202_4_normalize_metadata_data' has been applied
ryot        | [backend] 2024-04-03T23:46:04.548760Z  INFO sea_orm_migration::migrator: Applying migration 'm20240202_3_add_metadata_reason'
ryot        | [backend] 2024-04-03T23:46:04.548889Z  INFO sea_orm_migration::migrator: Migration 'm20240202_3_add_metadata_reason' has been applied
ryot        | [backend] 2024-04-03T23:46:04.549629Z  INFO sea_orm_migration::migrator: Applying migration 'm20240202_5_remove_default_value'
ryot        | [backend] 2024-04-03T23:46:04.568520Z  INFO sea_orm_migration::migrator: Migration 'm20240202_5_remove_default_value' has been applied
ryot        | [backend] 2024-04-03T23:46:04.569534Z  INFO sea_orm_migration::migrator: Applying migration 'm20240202_6_remove_last_processed_on_for_calendar'
ryot        | [backend] 2024-04-03T23:46:04.577805Z  INFO sea_orm_migration::migrator: Migration 'm20240202_6_remove_last_processed_on_for_calendar' has been applied
ryot        | [backend] 2024-04-03T23:46:04.578290Z  INFO sea_orm_migration::migrator: Applying migration 'm20240210_0_remove_duplicated_calendar_events'
ryot        | [backend] 2024-04-03T23:46:23.138067Z  INFO sea_orm_migration::migrator: Migration 'm20240210_0_remove_duplicated_calendar_events' has been applied
ryot        | [backend] 2024-04-03T23:46:23.147600Z  INFO sea_orm_migration::migrator: Applying migration 'm20240210_1_create_correct_calendar_event_index'
ryot        | [backend] 2024-04-03T23:46:51.549178Z  INFO sea_orm_migration::migrator: Migration 'm20240210_1_create_correct_calendar_event_index' has been applied
ryot        | [backend] 2024-04-03T23:46:51.552081Z  INFO sea_orm_migration::migrator: Applying migration 'm20240220_add_is_demo_column'
ryot        | [backend] 2024-04-03T23:46:51.658518Z  INFO sea_orm_migration::migrator: Migration 'm20240220_add_is_demo_column' has been applied
ryot        | [backend] 2024-04-03T23:46:51.659277Z  INFO sea_orm_migration::migrator: Applying migration 'm20240223_add_is_partial_field_to_person'
```

docker-compose-yml

```
version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - /home/user/ryot/data/db:/var/lib/postgresql/data

    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

    environment:
      - /etc/localtime:/etc/localtime:ro

  ryot:
    image: "ghcr.io/ignisda/ryot:latest"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - SERVER_INSECURE_COOKIE=true # only needed in localhost or non-https
      - /etc/localtime:/etc/localtime:ro
      - MOVIES_AND_SHOWS_TMDB_LOCALE=de
    ports:
      - "10000:8000"
    container_name: ryot

```

**Comment by IgnisDa** [comment]
Change the `SERVER_INSECURE_COOKIE` to `FRONTEND_INSECURE_COOKIES`.

**Comment by TWART016** [comment]
Still the same error with FRONTEND_INSECURE_COOKIES and without the environment variable.

**Comment by IgnisDa** [comment]
Are all the migrations being applied?

**Comment by TWART016** [comment]
How can I check that?

**Comment by IgnisDa** [comment]
Please dump the database and email it to me. I'll debug it locally.

**Comment by XyberDAWG** [comment]
I too am getting application errors all over the database. every other thing I do leads to one, then any media item i click on leads to an application error.

I can page through my media and it will randomly give an application error, refresh and it will work.

**Comment by IgnisDa** [comment]
@XyberDAWG What is the error in the docker logs?

**Comment by d7eeem** [comment]
for me also on the "export/import Page".

but apparently my minio container was off

**Comment by XyberDAWG** [comment]
> I too am getting application errors all over the database. every other thing I do leads to one, then any media item i click on leads to an application error.
> 
> I can page through my media and it will randomly give an application error, refresh and it will work.

Ok nevermind, a restart of my computer seemed to fix most of them.

The only one that still shows up is "export/import page" when trying to upload MAL imports.

**Comment by IgnisDa** [comment]
Which version are you running? This issue was fixed day before yesterday.

**Comment by XyberDAWG** [comment]
I am assuming it is 4.3.0. I am using Portainer for Docker Desktop. I am not sure how to properly update to Anything other than the Main release.

**Comment by IgnisDa** [comment]
Replace `ghcr.io/ignisda/ryot:v4.3.0` with `ghcr.io/ignisda/ryot:latest`. or `v4.3.17` if you want it to be more specific.

**Comment by TWART016** [comment]
I have sent you the dump by e-mail

**Comment by IgnisDa** [comment]
@TWART016 I have fixed the database bugs. Also you have ~30 migrations pending, it will take a minute to apply them all.

**Comment by TWART016** [comment]
Is this fixed in the latest Version 4.4.0?

**Comment by IgnisDa** [comment]
The latest version is `4.4.18`.

**Comment by TWART016** [comment]
I still get an error
`
ryot        | [frontend] [Error: Unexpected Server Error]
ryot        | [frontend] GET / 500 - - 815.364 ms
ryot        | [frontend] ClientError: Query Error: error returned from database: column user_to_entity.media_reason does not exist: {"response":{"data":null,"errors":[{"message":"Query Error: error returned from database: column user_to_entity.media_reason does not exist","locations":[{"line":2,"column":3}],"path":["userUpcomingCalendarEvents"]}],"status":200,"headers":{}},"request":{"query":"query UserUpcomingCalendarEvents($input: UserUpcomingCalendarEventInput!) {\n  userUpcomingCalendarEvents(input: $input) {\n    ...CalendarEventPart\n  }\n}\n\nfragment SeenShowExtraInformationPart on SeenShowExtraInformation {\n  episode\n  season\n}\n\nfragment SeenPodcastExtraInformationPart on SeenPodcastExtraInformation {\n  episode\n}\n\nfragment CalendarEventPart on GraphqlCalendarEvent {\n  calendarEventId\n  metadataId\n  metadataTitle\n  metadataLot\n  metadataImage\n  date\n  showExtraInformation {\n    ...SeenShowExtraInformationPart\n  }\n  podcastExtraInformation {\n    ...SeenPodcastExtraInformationPart\n  }\n}","variables":{"input":{"nextMedia":8}}}}
ryot        | [frontend]     at makeRequest (file:///home/ryot/node_modules/graphql-request/src/index.ts:426:11)
ryot        | [frontend]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
ryot        | [frontend]     at loader$5 (file:///home/ryot/build/server/index.js?t=1713401113000:12357:42)
ryot        | [frontend]     at Object.callRouteLoaderRR (/home/ryot/node_modules/@remix-run/server-runtime/dist/data.js:52:16)
ryot        | [frontend]     at callLoaderOrAction (/home/ryot/node_modules/@remix-run/router/router.ts:4043:16)
ryot        | [frontend]     at async Promise.all (index 2)
ryot        | [frontend]     at loadRouteData (/home/ryot/node_modules/@remix-run/router/router.ts:3320:19)
ryot        | [frontend]     at queryImpl (/home/ryot/node_modules/@remix-run/router/router.ts:3101:20)
ryot        | [frontend]     at Object.query (/home/ryot/node_modules/@remix-run/router/router.ts:2977:18)
ryot        | [frontend]     at handleDocumentRequestRR (/home/ryot/node_modules/@remix-run/server-runtime/dist/server.js:184:15) {
ryot        | [frontend]   response: {
ryot        | [frontend]     data: null,
ryot        | [frontend]     errors: [ [Object] ],
ryot        | [frontend]     status: 200,
ryot        | [frontend]     headers: Headers { [Symbol(map)]: [Object: null prototype] }
ryot        | [frontend]   },
ryot        | [frontend]   request: {
ryot        | [frontend]     query: 'query UserUpcomingCalendarEvents($input: UserUpcomingCalendarEventInput!) {\n' +
ryot        | [frontend]       '  userUpcomingCalendarEvents(input: $input) {\n' +
ryot        | [frontend]       '    ...CalendarEventPart\n' +
ryot        | [frontend]       '  }\n' +
ryot        | [frontend]       '}\n' +
ryot        | [frontend]       '\n' +
ryot        | [frontend]       'fragment SeenShowExtraInformationPart on SeenShowExtraInformation {\n' +
ryot        | [frontend]       '  episode\n' +
ryot        | [frontend]       '  season\n' +
ryot        | [frontend]       '}\n' +
ryot        | [frontend]       '\n' +
ryot        | [frontend]       'fragment SeenPodcastExtraInformationPart on SeenPodcastExtraInformation {\n' +
ryot        | [frontend]       '  episode\n' +
ryot        | [frontend]       '}\n' +
ryot        | [frontend]       '\n' +
ryot        | [frontend]       'fragment CalendarEventPart on GraphqlCalendarEvent {\n' +
ryot        | [frontend]       '  calendarEventId\n' +
ryot        | [frontend]       '  metadataId\n' +
ryot        | [frontend]       '  metadataTitle\n' +
ryot        | [frontend]       '  metadataLot\n' +
ryot        | [frontend]       '  metadataImage\n' +
ryot        | [frontend]       '  date\n' +
ryot        | [frontend]       '  showExtraInformation {\n' +
ryot        | [frontend]       '    ...SeenShowExtraInformationPart\n' +
ryot        | [frontend]       '  }\n' +
ryot        | [frontend]       '  podcastExtraInformation {\n' +
ryot        | [frontend]       '    ...SeenPodcastExtraInformationPart\n' +
ryot        | [frontend]       '  }\n' +
ryot        | [frontend]       '}',
ryot        | [frontend]     variables: { input: [Object] }
ryot        | [frontend]   }
ryot        | [frontend] }
ryot        | [frontend] [Error: Unexpected Server Error]
ryot        | [frontend] GET / 500 - - 143.605 ms
postgres_1  |
postgres_1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres_1  |
postgres_1  | 2024-04-18 22:39:10.390 UTC [1] LOG:  starting PostgreSQL 16.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 13.2.1_git20231014) 13.2.1 20231014, 64-bit
postgres_1  | 2024-04-18 22:39:10.412 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1  | 2024-04-18 22:39:10.412 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1  | 2024-04-18 22:39:10.435 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1  | 2024-04-18 22:39:10.535 UTC [23] LOG:  database system was shut down at 2024-04-18 22:35:59 UTC
postgres_1  | 2024-04-18 22:39:10.641 UTC [1] LOG:  database system is ready to accept connections
postgres_1  | 2024-04-18 22:39:46.491 UTC [31] ERROR:  column user_to_entity.media_reason does not exist at character 591
postgres_1  | 2024-04-18 22:39:46.491 UTC [31] STATEMENT:  SELECT "calendar_event"."id", "calendar_event"."date", "calendar_event"."metadata_id", "calendar_event"."metadata_show_extra_information", "calendar_event"."metadata_podcast_extra_information", "metadata"."lot" AS "m_lot", "metadata"."title" AS "m_title", "metadata"."images" AS "m_images", "metadata"."show_specifics" AS "m_show_specifics", "metadata"."podcast_specifics" AS "m_podcast_specifics" FROM "calendar_event" JOIN "metadata" ON "calendar_event"."metadata_id" = "metadata"."id" JOIN "user_to_entity" ON "user_to_entity"."metadata_id" = "calendar_event"."metadata_id" AND $1 = ANY("user_to_entity"."media_reason") WHERE "user_to_entity"."user_id" = $2 AND "calendar_event"."date" >= $3 ORDER BY "calendar_event"."date" ASC LIMIT $4
postgres_1  | 2024-04-18 22:39:47.770 UTC [28] ERROR:  column user_to_entity.media_reason does not exist at character 591
postgres_1  | 2024-04-18 22:39:47.770 UTC [28] STATEMENT:  SELECT "calendar_event"."id", "calendar_event"."date", "calendar_event"."metadata_id", "calendar_event"."metadata_show_extra_information", "calendar_event"."metadata_podcast_extra_information", "metadata"."lot" AS "m_lot", "metadata"."title" AS "m_title", "metadata"."images" AS "m_images", "metadata"."show_specifics" AS "m_show_specifics", "metadata"."podcast_specifics" AS "m_podcast_specifics" FROM "calendar_event" JOIN "metadata" ON "calendar_event"."metadata_id" = "metadata"."id" JOIN "user_to_entity" ON "user_to_entity"."metadata_id" = "calendar_event"."metadata_id" AND $1 = ANY("user_to_entity"."media_reason") WHERE "user_to_entity"."user_id" = $2 AND "calendar_event"."date" >= $3 ORDER BY "calendar_event"."date" ASC LIMIT $4
`
I also tried with version 5.0 (3c44e7535b3a)

**Comment by IgnisDa** [comment]
Did you do the major version upgrade correctly?
